language: r
cache: packages
sudo: false
fortran: false
latex: false
pandoc: false

matrix:
  include:
    - r: devel
    - os: osx
      osx_image: xcode9.3 #High Sierra
    - os: osx
      osx_image: xcode8.3 #Sierra
    - os: osx
      osx_image: xcode7.3 #El-Capitan

after_success:
  - test $R_CODECOV && Rscript -e 'covr::codecov()'

env:
  global:
    - NOT_CRAN=true
