language: r
cache: packages
sudo: false
fortran: false
latex: false
pandoc: false

matrix:
  include:
    - r: devel
    - os: osx
      osx_image: xcode9.3 #High Sierra
    - os: osx
      osx_image: xcode8.3 #Sierra
    - os: osx
      osx_image: xcode7.3 #El-Capitan

before_script:
  - ulimit -c unlimited -S       # enable core dumps
  - rm -rf /cores/core.*
  - rm -rf ~/Library/Logs/DiagnosticReports/*

after_success:
  - test $R_CODECOV && Rscript -e 'covr::codecov()'

after_failure:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      for c in $(ls /cores/core.*); do
        lldb -c $c -o "bt all" -b;
      done;
      for c in $(ls ~/Library/Logs/DiagnosticReports); do
        cat ~/Library/Logs/DiagnosticReports/$c;
      done;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      for c in $(ls core*); do
        gdb -c $c -ex bt -ex "set pagination 0" -batch;
      done;
    fi

env:
  global:
    - NOT_CRAN=true

addons:
  apt:
    packages:
    - gdb
